/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.model.PersistedAnimal;
import com.liferay.model.PersistedAnimalModel;
import com.liferay.model.PersistedAnimalSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PersistedAnimal service. Represents a row in the &quot;Animal_PersistedAnimal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PersistedAnimalModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersistedAnimalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedAnimalImpl
 * @generated
 */
@JSON(strict = true)
public class PersistedAnimalModelImpl
	extends BaseModelImpl<PersistedAnimal> implements PersistedAnimalModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persisted animal model instance should use the <code>PersistedAnimal</code> interface instead.
	 */
	public static final String TABLE_NAME = "Animal_PersistedAnimal";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"animalId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"animalClass", Types.VARCHAR},
		{"numberOfLegs", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("animalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("animalClass", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("numberOfLegs", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Animal_PersistedAnimal (uuid_ VARCHAR(75) null,animalId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,animalClass VARCHAR(75) null,numberOfLegs INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table Animal_PersistedAnimal";

	public static final String ORDER_BY_JPQL =
		" ORDER BY persistedAnimal.animalId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Animal_PersistedAnimal.animalId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ANIMALID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static PersistedAnimal toModel(PersistedAnimalSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PersistedAnimal model = new PersistedAnimalImpl();

		model.setUuid(soapModel.getUuid());
		model.setAnimalId(soapModel.getAnimalId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setAnimalClass(soapModel.getAnimalClass());
		model.setNumberOfLegs(soapModel.getNumberOfLegs());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<PersistedAnimal> toModels(
		PersistedAnimalSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<PersistedAnimal> models = new ArrayList<PersistedAnimal>(
			soapModels.length);

		for (PersistedAnimalSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PersistedAnimalModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _animalId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAnimalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _animalId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PersistedAnimal.class;
	}

	@Override
	public String getModelClassName() {
		return PersistedAnimal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PersistedAnimal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PersistedAnimal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAnimal, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PersistedAnimal)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PersistedAnimal, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PersistedAnimal, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PersistedAnimal)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PersistedAnimal, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PersistedAnimal, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PersistedAnimal>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PersistedAnimal.class.getClassLoader(), PersistedAnimal.class,
			ModelWrapper.class);

		try {
			Constructor<PersistedAnimal> constructor =
				(Constructor<PersistedAnimal>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PersistedAnimal, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PersistedAnimal, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PersistedAnimal, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<PersistedAnimal, Object>>();
		Map<String, BiConsumer<PersistedAnimal, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PersistedAnimal, ?>>();

		attributeGetterFunctions.put("uuid", PersistedAnimal::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PersistedAnimal, String>)PersistedAnimal::setUuid);
		attributeGetterFunctions.put("animalId", PersistedAnimal::getAnimalId);
		attributeSetterBiConsumers.put(
			"animalId",
			(BiConsumer<PersistedAnimal, Long>)PersistedAnimal::setAnimalId);
		attributeGetterFunctions.put("groupId", PersistedAnimal::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<PersistedAnimal, Long>)PersistedAnimal::setGroupId);
		attributeGetterFunctions.put(
			"companyId", PersistedAnimal::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PersistedAnimal, Long>)PersistedAnimal::setCompanyId);
		attributeGetterFunctions.put("userId", PersistedAnimal::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<PersistedAnimal, Long>)PersistedAnimal::setUserId);
		attributeGetterFunctions.put("userName", PersistedAnimal::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<PersistedAnimal, String>)PersistedAnimal::setUserName);
		attributeGetterFunctions.put(
			"createDate", PersistedAnimal::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PersistedAnimal, Date>)PersistedAnimal::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", PersistedAnimal::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PersistedAnimal, Date>)
				PersistedAnimal::setModifiedDate);
		attributeGetterFunctions.put("name", PersistedAnimal::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<PersistedAnimal, String>)PersistedAnimal::setName);
		attributeGetterFunctions.put(
			"animalClass", PersistedAnimal::getAnimalClass);
		attributeSetterBiConsumers.put(
			"animalClass",
			(BiConsumer<PersistedAnimal, String>)
				PersistedAnimal::setAnimalClass);
		attributeGetterFunctions.put(
			"numberOfLegs", PersistedAnimal::getNumberOfLegs);
		attributeSetterBiConsumers.put(
			"numberOfLegs",
			(BiConsumer<PersistedAnimal, Integer>)
				PersistedAnimal::setNumberOfLegs);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getAnimalId() {
		return _animalId;
	}

	@Override
	public void setAnimalId(long animalId) {
		_animalId = animalId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getAnimalClass() {
		if (_animalClass == null) {
			return "";
		}
		else {
			return _animalClass;
		}
	}

	@Override
	public void setAnimalClass(String animalClass) {
		_animalClass = animalClass;
	}

	@JSON
	@Override
	public int getNumberOfLegs() {
		return _numberOfLegs;
	}

	@Override
	public void setNumberOfLegs(int numberOfLegs) {
		_numberOfLegs = numberOfLegs;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(PersistedAnimal.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PersistedAnimal.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PersistedAnimal toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PersistedAnimal>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PersistedAnimalImpl persistedAnimalImpl = new PersistedAnimalImpl();

		persistedAnimalImpl.setUuid(getUuid());
		persistedAnimalImpl.setAnimalId(getAnimalId());
		persistedAnimalImpl.setGroupId(getGroupId());
		persistedAnimalImpl.setCompanyId(getCompanyId());
		persistedAnimalImpl.setUserId(getUserId());
		persistedAnimalImpl.setUserName(getUserName());
		persistedAnimalImpl.setCreateDate(getCreateDate());
		persistedAnimalImpl.setModifiedDate(getModifiedDate());
		persistedAnimalImpl.setName(getName());
		persistedAnimalImpl.setAnimalClass(getAnimalClass());
		persistedAnimalImpl.setNumberOfLegs(getNumberOfLegs());

		persistedAnimalImpl.resetOriginalValues();

		return persistedAnimalImpl;
	}

	@Override
	public int compareTo(PersistedAnimal persistedAnimal) {
		long primaryKey = persistedAnimal.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PersistedAnimal)) {
			return false;
		}

		PersistedAnimal persistedAnimal = (PersistedAnimal)object;

		long primaryKey = persistedAnimal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		PersistedAnimalModelImpl persistedAnimalModelImpl = this;

		persistedAnimalModelImpl._originalUuid = persistedAnimalModelImpl._uuid;

		persistedAnimalModelImpl._originalGroupId =
			persistedAnimalModelImpl._groupId;

		persistedAnimalModelImpl._setOriginalGroupId = false;

		persistedAnimalModelImpl._originalCompanyId =
			persistedAnimalModelImpl._companyId;

		persistedAnimalModelImpl._setOriginalCompanyId = false;

		persistedAnimalModelImpl._setModifiedDate = false;

		persistedAnimalModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PersistedAnimal> toCacheModel() {
		PersistedAnimalCacheModel persistedAnimalCacheModel =
			new PersistedAnimalCacheModel();

		persistedAnimalCacheModel.uuid = getUuid();

		String uuid = persistedAnimalCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			persistedAnimalCacheModel.uuid = null;
		}

		persistedAnimalCacheModel.animalId = getAnimalId();

		persistedAnimalCacheModel.groupId = getGroupId();

		persistedAnimalCacheModel.companyId = getCompanyId();

		persistedAnimalCacheModel.userId = getUserId();

		persistedAnimalCacheModel.userName = getUserName();

		String userName = persistedAnimalCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			persistedAnimalCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			persistedAnimalCacheModel.createDate = createDate.getTime();
		}
		else {
			persistedAnimalCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			persistedAnimalCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			persistedAnimalCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		persistedAnimalCacheModel.name = getName();

		String name = persistedAnimalCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			persistedAnimalCacheModel.name = null;
		}

		persistedAnimalCacheModel.animalClass = getAnimalClass();

		String animalClass = persistedAnimalCacheModel.animalClass;

		if ((animalClass != null) && (animalClass.length() == 0)) {
			persistedAnimalCacheModel.animalClass = null;
		}

		persistedAnimalCacheModel.numberOfLegs = getNumberOfLegs();

		return persistedAnimalCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PersistedAnimal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PersistedAnimal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAnimal, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((PersistedAnimal)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PersistedAnimal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PersistedAnimal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAnimal, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PersistedAnimal)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PersistedAnimal>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _animalId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _animalClass;
	private int _numberOfLegs;
	private long _columnBitmask;
	private PersistedAnimal _escapedModel;

}