/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedAnimal service. Represents a row in the &quot;Animal_PersistedAnimal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.model.impl.PersistedAnimalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.model.impl.PersistedAnimalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedAnimal
 * @generated
 */
@ProviderType
public interface PersistedAnimalModel
	extends BaseModel<PersistedAnimal>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted animal model instance should use the {@link PersistedAnimal} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted animal.
	 *
	 * @return the primary key of this persisted animal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted animal.
	 *
	 * @param primaryKey the primary key of this persisted animal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this persisted animal.
	 *
	 * @return the uuid of this persisted animal
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this persisted animal.
	 *
	 * @param uuid the uuid of this persisted animal
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the animal ID of this persisted animal.
	 *
	 * @return the animal ID of this persisted animal
	 */
	public long getAnimalId();

	/**
	 * Sets the animal ID of this persisted animal.
	 *
	 * @param animalId the animal ID of this persisted animal
	 */
	public void setAnimalId(long animalId);

	/**
	 * Returns the group ID of this persisted animal.
	 *
	 * @return the group ID of this persisted animal
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this persisted animal.
	 *
	 * @param groupId the group ID of this persisted animal
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this persisted animal.
	 *
	 * @return the company ID of this persisted animal
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persisted animal.
	 *
	 * @param companyId the company ID of this persisted animal
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persisted animal.
	 *
	 * @return the user ID of this persisted animal
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persisted animal.
	 *
	 * @param userId the user ID of this persisted animal
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persisted animal.
	 *
	 * @return the user uuid of this persisted animal
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persisted animal.
	 *
	 * @param userUuid the user uuid of this persisted animal
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persisted animal.
	 *
	 * @return the user name of this persisted animal
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persisted animal.
	 *
	 * @param userName the user name of this persisted animal
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persisted animal.
	 *
	 * @return the create date of this persisted animal
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persisted animal.
	 *
	 * @param createDate the create date of this persisted animal
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persisted animal.
	 *
	 * @return the modified date of this persisted animal
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persisted animal.
	 *
	 * @param modifiedDate the modified date of this persisted animal
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this persisted animal.
	 *
	 * @return the name of this persisted animal
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this persisted animal.
	 *
	 * @param name the name of this persisted animal
	 */
	public void setName(String name);

	/**
	 * Returns the animal class of this persisted animal.
	 *
	 * @return the animal class of this persisted animal
	 */
	@AutoEscape
	public String getAnimalClass();

	/**
	 * Sets the animal class of this persisted animal.
	 *
	 * @param animalClass the animal class of this persisted animal
	 */
	public void setAnimalClass(String animalClass);

	/**
	 * Returns the number of legs of this persisted animal.
	 *
	 * @return the number of legs of this persisted animal
	 */
	public int getNumberOfLegs();

	/**
	 * Sets the number of legs of this persisted animal.
	 *
	 * @param numberOfLegs the number of legs of this persisted animal
	 */
	public void setNumberOfLegs(int numberOfLegs);

}